image: node:latest

cache:
  paths:
  - node_modules/

# Build stages

stages:
  - install
  - build

### Jobs ###

# Install dependencies, compile the bundle.js
install-dependencies:
  stage: install
  before_script:
    - npm i -g npm
  script:
    - npm ci
  artifacts:
    paths:
      - semantic/
      - node_modules/

build:
  stage: build
  before_script:
    - npm i -g npm webpack
  script:
    - webpack -v
    - npm run build
  artifacts:
    paths:
      - build/
